using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TextChanger : MonoBehaviour {
    
    private Text txt;
    
    //[HideInInspector]
    public string defaultText;

    [SerializeField]
    bool isLoadingUI;

    private void Start()
    {
        txt = GetComponent<Text>();
        if(!isLoadingUI)
            StartCoroutine(ChangeWordsRandomly());
        else
            StartCoroutine(ShowLoadingScenario());

    }

    IEnumerator ChangeWordsRandomly()
    {
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
#endregion
        yield return new WaitForSeconds(0.02f);
        txt.text = defaultText;
        yield return new WaitForSeconds(2f);
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        yield return new WaitForSeconds(1f);
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        yield return new WaitForSeconds(1f);
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        yield return new WaitForSeconds(1f);
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        yield return new WaitForSeconds(1f);
        #region GlitchLetters
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        yield return new WaitForSeconds(0.02f);
        txt.text = "N N 0 0 1";
        yield return new WaitForSeconds(0.02f);
        txt.text = "0 1 1 1 0";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G Y A X E";
        yield return new WaitForSeconds(0.02f);
        txt.text = "T D M Y S";
        yield return new WaitForSeconds(0.02f);
        txt.text = "X S W 3 F";
        yield return new WaitForSeconds(0.02f);
        txt.text = "G M Y T X";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Q P W X 4";
        yield return new WaitForSeconds(0.02f);
        txt.text = "Z S W Y 9";
        #endregion
        txt.text = defaultText;
        yield return new WaitForSeconds(4f);
        Destroy(gameObject, 0.1f);
    }

    IEnumerator ShowLoadingScenario()
    {
        yield return new WaitForSeconds(2f);
        txt.text = defaultText + " .";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ..";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ...";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " .";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ..";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ...";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " .";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ..";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ...";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " .";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ..";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ...";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " .";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ..";
        yield return new WaitForSeconds(1f);
        txt.text = defaultText + " ...";
        yield return new WaitForSeconds(1f);

    }
}
